name: flutter_application_16
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PKUttaradit
      fonts:
        - asset: lib/fonts/PK_Uttaradit-Medium.ttf  # ตำแหน่งของไฟล์ฟอนต์ในโปรเจกต์ของคุณ
